
package nomina.Formularios;

import com.sun.rowset.internal.Row;
import java.awt.Button;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import nomina.Clases.ClsConexionDatos;
import nomina.Clases.ClsEmpleados;

/**
 *
 * @author  Wilson  Otalvaro Bedoya
 *          Victor Higuita 
 *          Juliana Toro
 */
public class FrmEmpleados extends javax.swing.JInternalFrame {

    
    ClsConexionDatos datos = new ClsConexionDatos();
    ClsEmpleados emp = new ClsEmpleados();
    ResultSet rs;
    ClsEmpleados p;
    int fila=0;
    int Fila = 1;
    int Max = 1;
    String Cargo = "";
    public FrmEmpleados() {
        initComponents();
        this.setSize(1345, 650);
        this.setVisible(true);       
        BtnGrabar.setEnabled(false);
        BtnDeshacer.setEnabled(false);
        inhabilitar();
        BtnModificar.setVisible(false);        
        Fila = 1;
        ExtraerDatos(Fila);   
        CBoxCedulas.setVisible(false);
    }
                   
    
    
    public void inhabilitar(){
    TxtCedula.setEnabled(false);
    TxtPrimerApellido.setEnabled(false);
    TxtSegundoApellido.setEnabled(false);
    TxtPrimerNombre.setEnabled(false);
    TxtSegundoNombre.setEnabled(false);
    TxtDireccion.setEnabled(false);
    TxtCorreElectronico.setEnabled(false);
    TxtTelefono.setEnabled(false);
    TxtCelular.setEnabled(false);
    TxtSalario.setEnabled(false);
    TxtFechaIngreso.setEnabled(false);
    TxtFechaSalida.setEnabled(false);
    CboTipoSalario.setEnabled(false);
    TxtFechaNacimiento.setEnabled(false);
    CboEstadoCivil.setEnabled(false);
    CboTipoSalario.setEnabled(false);
    TxtDiasTrabajados.setEnabled(false);
    TxtCuentaBancaria.setEnabled(false);
    TxtAuxTransporte.setEnabled(false);
    CBoxCargos.setEnabled(false);
    CboEstado.setEnabled(false);
    }
    
    public void habilitar() {
        TxtCedula.setEnabled(true);
        TxtPrimerApellido.setEnabled(true);
        TxtSegundoApellido.setEnabled(true);
        TxtPrimerNombre.setEnabled(true);
        TxtSegundoNombre.setEnabled(true);
        TxtDireccion.setEnabled(true);
        TxtCorreElectronico.setEnabled(true);
        TxtTelefono.setEnabled(true);
        TxtCelular.setEnabled(true);
        TxtSalario.setEnabled(true);
        TxtFechaIngreso.setEnabled(true);
        TxtFechaSalida.setEnabled(true);
        CboTipoSalario.setEnabled(true);
        TxtFechaNacimiento.setEnabled(true);
        TxtAuxTransporte.setEnabled(true);
        CboEstadoCivil.setEnabled(true);
        CBoxCargos.setEnabled(true);
        
        
        TxtDiasTrabajados.setEnabled(true);
        TxtCuentaBancaria.setEnabled(true);
    }
    private void limpiar(){
        TxtCedula.setText("");
        TxtPrimerApellido.setText("");
        TxtSegundoApellido.setText("");
        TxtPrimerNombre.setText("");
        TxtSegundoNombre.setText("");
        TxtDireccion.setText("");
    TxtCorreElectronico.setText("");
    TxtTelefono.setText("");
    TxtCelular.setText("");
    TxtSalario.setText("");
    TxtFechaIngreso.setText("");
    TxtFechaSalida.setText("");
    //CboTipoSalario.setText("");
    TxtFechaNacimiento.setText("");
    TxtDiasTrabajados.setText("");
    TxtCuentaBancaria.setText("");
    TxtAuxTransporte.setText("");
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtPrimerApellido = new javax.swing.JTextField();
        TxtSegundoApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtPrimerNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtCorreElectronico = new javax.swing.JTextField();
        TxtCelular = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        TxtFechaIngreso = new javax.swing.JTextField();
        TxtFechaSalida = new javax.swing.JTextField();
        TxtFechaNacimiento = new javax.swing.JTextField();
        CboTipoSalario = new javax.swing.JComboBox();
        CboEstadoCivil = new javax.swing.JComboBox();
        TxtDiasTrabajados = new javax.swing.JTextField();
        TxtCuentaBancaria = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CBoxCargos = new javax.swing.JComboBox();
        CboEstado = new javax.swing.JComboBox();
        TxtAuxTransporte = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BtnPrimero = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnSiguiiente = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnGrabar = new javax.swing.JButton();
        BtnDeshacer = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        CBoxCedulas = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Empleados");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 50, 20);

        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        TxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(TxtCedula);
        TxtCedula.setBounds(120, 30, 120, 20);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Primer Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 90, 20);

        TxtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrimerApellidoActionPerformed(evt);
            }
        });
        TxtPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerApellido);
        TxtPrimerApellido.setBounds(100, 30, 120, 20);

        TxtSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoApellido);
        TxtSegundoApellido.setBounds(400, 30, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Segundo Apellido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 30, 97, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Correo Electronico");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 110, 110, 20);
        jPanel1.add(TxtDireccion);
        TxtDireccion.setBounds(100, 110, 170, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Segundo Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 70, 98, 20);

        TxtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoNombre);
        TxtSegundoNombre.setBounds(400, 70, 120, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Primer Nombre");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 85, 20);

        TxtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerNombre);
        TxtPrimerNombre.setBounds(100, 70, 120, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 110, 52, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Cta Bancaria");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 290, 80, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("celular");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 140, 52, 20);

        TxtCorreElectronico.setForeground(new java.awt.Color(0, 0, 204));
        TxtCorreElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreElectronicoActionPerformed(evt);
            }
        });
        TxtCorreElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCorreElectronicoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtCorreElectronico);
        TxtCorreElectronico.setBounds(400, 110, 170, 20);

        TxtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCelularKeyTyped(evt);
            }
        });
        jPanel1.add(TxtCelular);
        TxtCelular.setBounds(400, 140, 120, 20);

        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtTelefono);
        TxtTelefono.setBounds(100, 140, 110, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Telefono");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 140, 48, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Salario Dia");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 170, 70, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Fecha Ingreso");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(290, 170, 100, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Fecha Salida");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 200, 100, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Tipo Salario");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 200, 100, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Cargo");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 260, 80, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Estado Civil");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(290, 230, 100, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Estado");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(290, 260, 100, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Aux Transporte");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 320, 100, 20);

        TxtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioActionPerformed(evt);
            }
        });
        TxtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSalarioKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSalario);
        TxtSalario.setBounds(100, 170, 110, 20);
        jPanel1.add(TxtFechaIngreso);
        TxtFechaIngreso.setBounds(400, 170, 120, 20);
        jPanel1.add(TxtFechaSalida);
        TxtFechaSalida.setBounds(100, 200, 110, 20);
        jPanel1.add(TxtFechaNacimiento);
        TxtFechaNacimiento.setBounds(100, 230, 110, 20);

        CboTipoSalario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fijo", "Variable" }));
        CboTipoSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboTipoSalarioActionPerformed(evt);
            }
        });
        jPanel1.add(CboTipoSalario);
        CboTipoSalario.setBounds(400, 200, 110, 20);

        CboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero", "Casado", "Separado" }));
        jPanel1.add(CboEstadoCivil);
        CboEstadoCivil.setBounds(400, 230, 110, 20);

        TxtDiasTrabajados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDiasTrabajadosKeyTyped(evt);
            }
        });
        jPanel1.add(TxtDiasTrabajados);
        TxtDiasTrabajados.setBounds(100, 290, 110, 20);
        jPanel1.add(TxtCuentaBancaria);
        TxtCuentaBancaria.setBounds(400, 290, 110, 20);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Fecha Nac");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 230, 80, 20);

        CBoxCargos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Analista" }));
        CBoxCargos.setToolTipText("");
        CBoxCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBoxCargosMouseClicked(evt);
            }
        });
        CBoxCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxCargosActionPerformed(evt);
            }
        });
        jPanel1.add(CBoxCargos);
        CBoxCargos.setBounds(100, 260, 150, 20);

        CboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jPanel1.add(CboEstado);
        CboEstado.setBounds(400, 260, 110, 20);

        TxtAuxTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAuxTransporteActionPerformed(evt);
            }
        });
        TxtAuxTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAuxTransporteKeyTyped(evt);
            }
        });
        jPanel1.add(TxtAuxTransporte);
        TxtAuxTransporte.setBounds(100, 320, 110, 20);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Dias Trabajados");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 290, 100, 20);

        jTabbedPane1.addTab("Datos Personales", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 60, 660, 380);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Datos Personales");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        BtnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Primero.jpg"))); // NOI18N
        BtnPrimero.setText("Primero");
        BtnPrimero.setToolTipText("Primer Registro");
        BtnPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPrimero.setName(""); // NOI18N
        BtnPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrimero);
        BtnPrimero.setBounds(70, 460, 90, 60);

        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Anterior.jpg"))); // NOI18N
        BtnAnterior.setText("Anterior");
        BtnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAnterior);
        BtnAnterior.setBounds(190, 460, 90, 60);

        BtnSiguiiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Siguiente.jpg"))); // NOI18N
        BtnSiguiiente.setText("Siguiente");
        BtnSiguiiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSiguiiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSiguiiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguiienteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSiguiiente);
        BtnSiguiiente.setBounds(320, 460, 90, 60);

        BtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Ultimo.jpg"))); // NOI18N
        BtnUltimo.setText("Ultimo");
        BtnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUltimo);
        BtnUltimo.setBounds(440, 460, 90, 60);

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Editar.jpg"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditar);
        BtnEditar.setBounds(760, 170, 90, 60);

        BtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Grabar.jpg"))); // NOI18N
        BtnGrabar.setText("Grabar");
        BtnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGrabar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGrabar);
        BtnGrabar.setBounds(760, 240, 90, 60);

        BtnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Deshacer1.jpg"))); // NOI18N
        BtnDeshacer.setText("Deshacer");
        BtnDeshacer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnDeshacer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnDeshacer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeshacerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDeshacer);
        BtnDeshacer.setBounds(760, 310, 90, 60);

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Salir.jpg"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(760, 460, 90, 60);

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/05.jpg"))); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNuevo);
        BtnNuevo.setBounds(760, 100, 90, 60);

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Deshacer.jpg"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar);
        BtnEliminar.setBounds(760, 380, 90, 60);

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Modificar.jpg"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnModificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificar);
        BtnModificar.setBounds(760, 240, 90, 60);

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/buscarlupa.jpg"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(610, 460, 90, 60);

        CBoxCedulas.setToolTipText("");
        CBoxCedulas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBoxCedulasItemStateChanged(evt);
            }
        });
        CBoxCedulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxCedulasActionPerformed(evt);
            }
        });
        getContentPane().add(CBoxCedulas);
        CBoxCedulas.setBounds(250, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeroActionPerformed
         Fila = 1;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnPrimeroActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
        CBoxCargos.setVisible(true);
        
        CBoxCargos.removeAllItems();
        habilitar();
        limpiar();
        ArrayList List = ClsConexionDatos.LlenarCBoxCargos();
        
        for (int i=0;i<List.size();i++){
                CBoxCargos.addItem(List.get(i));
        }      
        
        ArrayList List1 = ClsConexionDatos.LlenarCBoxCedulas();
        
        for (int i=0;i<List.size();i++){
                CBoxCedulas.addItem(List1.get(i));
        }
        
        BtnGrabar.setEnabled(true);
        BtnDeshacer.setEnabled(true);
        BtnEditar.setEnabled(false);
        BtnNuevo.setEnabled(false);
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        BtnEliminar.setEnabled(false);
        TxtCedula.setVisible(true);
        TxtCedula.setEnabled(true);
        TxtCedula.requestFocus();
        TxtCedula.setText("");
        BtnBuscar.setEnabled(false);
        CBoxCargos.setEnabled(true);
        
        
        CBoxCedulas.setVisible(false);
        habilitar();
        limpiar();
        TxtFechaIngreso.setText("aaaa/mm/dd");
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        BtnNuevo.setEnabled(false);
        BtnDeshacer.setEnabled(true);
        BtnGrabar.setVisible(false);
        BtnEliminar.setEnabled(false);
        BtnModificar.setVisible(true);
        BtnEditar.setEnabled(false);
        BtnBuscar.setEnabled(false);
        CBoxCargos.setEnabled(true);
        
        
        habilitar();
        TxtCedula.setEnabled(false);
        CBoxCargos.setVisible(true);
        //CBoxCargos.removeAllItems();
        
        ArrayList List = ClsConexionDatos.LlenarCBoxCargos();
        
        for (int i=0;i<List.size();i++){
                CBoxCargos.addItem(List.get(i));
        }      
        
        
        
        
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeshacerActionPerformed
        // TODO add your handling code here:
        BtnNuevo.setEnabled(true);
        BtnGrabar.setVisible(true);
        BtnGrabar.setEnabled(false);
        BtnDeshacer.setEnabled(false);
        BtnEditar.setEnabled(true);
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        limpiar();
        Fila = 1;
        ExtraerDatos(Fila);
        inhabilitar();
        BtnEliminar.setEnabled(true);
        BtnModificar.setVisible(false);
        BtnBuscar.setEnabled(true);
        CBoxCargos.setEnabled(false);
        
        
    }//GEN-LAST:event_BtnDeshacerActionPerformed

    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed
        
        char tecla=0;
        
        if(TxtCedula.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar cedula"); 
            TxtCedula.requestFocus();
            return;          
        }  
        CBoxCargos.setVisible(false);
        
        if (TxtCedula.getText().length() != 0) {
            try {

                if (datos.selectEmpleado(TxtCedula.getText()) == 1) {
                    JOptionPane.showMessageDialog(null, "Empleado ya existe: " + TxtCedula.getText());
                    TxtCedula.requestFocus();
                    return;
                }
            } catch (Exception e) {
            }
            //setVisible(false);
        }
        
        
        if (TxtCorreElectronico.getText().length()!=0){
            isEmail(TxtCorreElectronico.getText());
            if(( isEmail(TxtCorreElectronico.getText())==(false))){
                TxtCorreElectronico.requestFocus();
                return;
            }
            
        }
        if(TxtPrimerApellido.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar El Primer Apellido");
           TxtPrimerApellido.requestFocus();
            return;
        }         
         if(TxtPrimerNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar El Primer Nombre");
           TxtPrimerNombre.requestFocus();
            return;
        }         
        if(TxtDireccion.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar La Direccion");
           TxtDireccion.requestFocus();
            return;
        } 
        if(TxtCorreElectronico.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar EL  Correo Electronico");
           TxtCorreElectronico.requestFocus();
            return;              
        } 
        if(TxtSalario.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar el Salario");
           TxtSalario.requestFocus();
            return;
        } 
        if(TxtFechaIngreso.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar La Fecha de ingreso");
           TxtFechaIngreso.requestFocus();
            return;
        } 
        if(TxtAuxTransporte.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar El Auxilio de transporte");
           TxtAuxTransporte.requestFocus();
            return;
        } 
        
         if ((TxtFechaIngreso.getText().compareTo("aaaa/mm/dd") == 0) || (TxtFechaIngreso.getText().length() < 10) || (TxtFechaIngreso.getText().length() > 10)) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar La Fecha de ingreso aaaa/mm/dd");
            TxtFechaIngreso.requestFocus();
            return;
        } else {
            //Validamos Fecha            
            String FechaTemp = TxtFechaIngreso.getText();
            int Dia = Integer.parseInt(FechaTemp.substring(8, 10));
            int Mes = Integer.parseInt(FechaTemp.substring(5, 7));
            System.out.println(Dia + " " + Mes);
            if (FechaTemp.charAt(4) != '/' || FechaTemp.charAt(7) != '-') {
                System.out.println("Entro a letras");
                JOptionPane.showMessageDialog(rootPane, "Debe digitar La Fecha de ingreso aaaa/mm/dd");
                TxtFechaIngreso.requestFocus();
                return;
            } else if (Dia < 1 || Dia > 31 || Mes < 0 || Mes > 12) {
                System.out.println("Entro a num");
                JOptionPane.showMessageDialog(rootPane, "Debe digitar La Fecha de ingreso aaaa/mm/dd");
                TxtFechaIngreso.requestFocus();
                return;
            }
        }

        {
        int numFilas = 0;

                try {
                    emp = new ClsEmpleados();
                    emp.setCedula(TxtCedula.getText());
                    emp.setPrimerApellido(TxtPrimerApellido.getText());
                    emp.setSegundoApellido  (TxtSegundoApellido.getText());
                    emp.setPrimerNombre(TxtPrimerNombre.getText());
                    emp.setSegundoNombre(TxtSegundoNombre.getText());
                    emp.setDireccion(TxtDireccion.getText());
                    emp.setCorreoElectronico(TxtCorreElectronico.getText());
                    emp.setTelefono(TxtTelefono.getText());
                    emp.setCelular(TxtCelular.getText());
                    emp.setSalarioDia(Double.parseDouble(TxtSalario.getText()));
                    emp.setFechaIngreso(TxtFechaIngreso.getText());
                    emp.setFechaSalida(TxtFechaSalida.getText());
                    emp.setTipoSalario(CboTipoSalario.getSelectedItem().toString());
                    emp.setFechaNac(TxtFechaNacimiento.getText());
                    emp.setEstCivil(CboEstadoCivil.getSelectedItem().toString());
                    emp.setCargo(CBoxCargos.getSelectedItem().toString());
                    emp.setEstado(CboEstado.getSelectedItem().toString());
                    emp.setDiasTrabajados(Integer.parseInt( TxtDiasTrabajados.getText()));
                    emp.setCuentaBanc(TxtCuentaBancaria.getText());
                    emp.setAuxTransporte(Double.parseDouble(TxtAuxTransporte.getText()));
                    
                    numFilas = datos.Insert(emp.getCedula(),
                            emp.getPrimerApellido(),
                            emp.getSegundoApellido(),
                            emp.getPrimerNombre(),
                            emp.getSegundoNombre(),
                            emp.getDireccion(),
                            emp.getCorreoElectronico(),
                            emp.getTelefono(),
                            emp.getCelular(),
                            emp.getSalarioDia(),
                            emp.getFechaIngreso(),
                            emp.getFechaSalida(),
                            emp.getTipoSalario(),
                            emp.getFechaNac(),
                            emp.getEstCivil(),
                            emp.getCargo(),
                            emp.getEstado(),
                            emp.getDiasTrabajados(),
                            emp.getCuentaBanc(),
                            emp.getAuxTransporte()
                            );
                    JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " Registros Guardados !!!");

                } catch (Exception ee) {
                    System.out.println(ee.getStackTrace());
                    JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " error !!!");
                }
        }
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnGrabar.setEnabled(false);
        BtnNuevo.setEnabled(true);
        BtnEditar.setEnabled(true);
        BtnBuscar.setEnabled(true);        
        inhabilitar();
    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void TxtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioActionPerformed
        
    }//GEN-LAST:event_TxtSalarioActionPerformed

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed
        
        
    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void TxtPrimerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido
            
            
        }
    }//GEN-LAST:event_TxtPrimerApellidoKeyTyped

    private void TxtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrimerApellidoActionPerformed

    private void TxtSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido
            
            
        }
    }//GEN-LAST:event_TxtSegundoApellidoKeyTyped

    private void TxtPrimerNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerNombreKeyTyped
           char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido
            
            
        } 
    }//GEN-LAST:event_TxtPrimerNombreKeyTyped

    private void TxtSegundoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido
                       
        }
    }//GEN-LAST:event_TxtSegundoNombreKeyTyped

    private void TxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido
            
            
        }
        if(tecla==KeyEvent.VK_ENTER){
            try    
        {
                        
        datos.buscarEmpleado(TxtCedula.getText());
        TxtCedula.requestFocus();
        }
        catch (Exception e)
                {
                    
                }
        //setVisible(false);
        }
    }//GEN-LAST:event_TxtCedulaKeyTyped

    private void TxtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSalarioKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido
            
            
        }
    }//GEN-LAST:event_TxtSalarioKeyTyped

    private void BtnSiguiienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguiienteActionPerformed
        Max = ClsConexionDatos.NumeroFilas();
        if (Fila < Max){
            Fila++;
        }        
        ExtraerDatos(Fila);        
    }//GEN-LAST:event_BtnSiguiienteActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
         if (Fila > 1){
            Fila--;
        }        
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
       Max = ClsConexionDatos.NumeroFilas();
        Fila = Max;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void CboTipoSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboTipoSalarioActionPerformed
        
  
    }//GEN-LAST:event_CboTipoSalarioActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        datos.DeleteEmpleados(TxtCedula.getText());
        limpiar();
        inhabilitar();
        Fila = 1;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        BtnNuevo.setEnabled(true);
        BtnEditar.setEnabled(true);
        BtnModificar.setVisible(false);
        BtnGrabar.setVisible(true);
        BtnGrabar.setEnabled(false);
        
        char tecla=0;
        String cedula="";
        if(TxtCedula.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar cedula"); 
            TxtCedula.requestFocus();
            return;          
        }  
        //CBoxCargos.setVisible(false);
        
//        if (TxtCedula.getText().length() != 0) {
//            try {
//
//                if (datos.selectEmpleado(TxtCedula.getText()) == 1) {
//                    JOptionPane.showMessageDialog(null, "Empleado ya existe: " + TxtCedula.getText());
//                    TxtCedula.requestFocus();
//                    return;
//                }
//            } catch (Exception e) {
//            }
//            //setVisible(false);
//        }
        
        
        if (TxtCorreElectronico.getText().length()!=0){
            isEmail(TxtCorreElectronico.getText());
            if(( isEmail(TxtCorreElectronico.getText())==(false))){
                TxtCorreElectronico.requestFocus();
                return;
            }
            
        }
        if(TxtPrimerApellido.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar El Primer Apellido");
           TxtPrimerApellido.requestFocus();
            return;
        }         
         if(TxtPrimerNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar El Primer Nombre");
           TxtPrimerNombre.requestFocus();
            return;
        }         
        if(TxtDireccion.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar La Direccion");
           TxtDireccion.requestFocus();
            return;
        } 
        if(TxtCorreElectronico.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar EL  Correo Electronico");
           TxtCorreElectronico.requestFocus();
            return;              
        } 
        if(TxtSalario.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar el Salario");
           TxtSalario.requestFocus();
            return;
        } 
        if(TxtFechaIngreso.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar La Fecha de ingreso");
           TxtFechaIngreso.requestFocus();
            return;
        } 



        {
        int numFilas = 0;

                try {
                    emp = new ClsEmpleados();
                    emp.setCedula(TxtCedula.getText());
                    emp.setPrimerApellido(TxtPrimerApellido.getText());
                    emp.setSegundoApellido  (TxtSegundoApellido.getText());
                    emp.setPrimerNombre(TxtPrimerNombre.getText());
                    emp.setSegundoNombre(TxtSegundoNombre.getText());
                    emp.setDireccion(TxtDireccion.getText());
                    emp.setCorreoElectronico(TxtCorreElectronico.getText());
                    emp.setTelefono(TxtTelefono.getText());
                    emp.setCelular(TxtCelular.getText());
                    emp.setSalarioDia(Double.parseDouble(TxtSalario.getText()));
                    emp.setFechaIngreso(TxtFechaIngreso.getText());
                    emp.setFechaSalida(TxtFechaSalida.getText());
                    emp.setTipoSalario(CboTipoSalario.getSelectedItem().toString());
                    
                    emp.setFechaNac(TxtFechaNacimiento.getText());
                    emp.setEstCivil(CboEstadoCivil.getSelectedItem().toString());
                    
                   // emp.setCargo(Cargo); //Esto se cargó en el listener
                    //emp.setCargo(TxtCargo.getText());
                    emp.setCargo(CBoxCargos.getSelectedItem().toString());
                    emp.setEstado(CboEstado.getSelectedItem().toString());
                    emp.setDiasTrabajados(Integer.parseInt( TxtDiasTrabajados.getText()));
                    emp.setCuentaBanc(TxtCuentaBancaria.getText());
                    emp.setAuxTransporte(Double.parseDouble(TxtAuxTransporte.getText()));
                    
                    numFilas = datos.Update(emp.getCedula(),
                            emp.getPrimerApellido(),
                            emp.getSegundoApellido(),
                            emp.getPrimerNombre(),
                            emp.getSegundoNombre(),
                            emp.getDireccion(),
                            emp.getCorreoElectronico(),
                            emp.getTelefono(),
                            emp.getCelular(),
                            emp.getSalarioDia(),
                            emp.getFechaIngreso(),
                            emp.getFechaSalida(),
                            emp.getTipoSalario(),
                            emp.getFechaNac(),
                            emp.getEstCivil(),
                            emp.getCargo(),
                            emp.getEstado(),
                            emp.getDiasTrabajados(),
                            emp.getCuentaBanc(),
                            emp.getAuxTransporte()
                            );
                    JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " Registros Guardados !!!");

                } catch (Exception ee) {
                    System.out.println(ee.getStackTrace());
                    JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " error !!!");
                }
        }
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnGrabar.setEnabled(false);
        BtnNuevo.setEnabled(true);
        BtnEditar.setEnabled(true);
        BtnBuscar.setEnabled(true);        
        inhabilitar();
        
        
        
        
        
        
        
        BtnBuscar.setEnabled(true); 
        //CBoxCargos.setVisible(false);
                
        
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        int x=0;
        if(TxtPrimerApellido.getText().length()!=0){
            x=1;
        }
        else
        {
            x=2;
        }
       
        if (x==1){
        
        limpiar();
        CBoxCedulas.removeAllItems();
        CBoxCedulas.setEnabled(true);       
        
        ArrayList List = ClsConexionDatos.LlenarCBoxCedulas();
        
        for (int i=0;i<List.size();i++){
                CBoxCedulas.addItem(List.get(i));
        }
        
        CBoxCedulas.requestFocus();
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        BtnNuevo.setEnabled(false);
        BtnEditar.setEnabled(false);
        BtnGrabar.setEnabled(false);
        BtnDeshacer.setEnabled(true);
        BtnEliminar.setEnabled(false);
        CBoxCedulas.setVisible(true);
        TxtCedula.setVisible(false);
       
       if (TxtCedula.getText().length() == 0){
            //JOptionPane.showMessageDialog(rootPane,"Debe digitar cedula"); 
            TxtCedula.requestFocus();
            
        }  
        }
         if(x==2){

             Fila = 1;
        cargarDatos(TxtCedula.getText());
        BtnNuevo.setEnabled(true);
        BtnModificar.setEnabled(true);
        BtnEliminar.setEnabled(true);
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnEditar.setEnabled(true);
        CBoxCedulas.setVisible(true);
        TxtCedula.setVisible(false);
        
                
       }
        
       
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void CBoxCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxCargosActionPerformed

      //  Cargo = String.valueOf(CBoxCargos.getSelectedIndex());
    }//GEN-LAST:event_CBoxCargosActionPerformed

    private void TxtCorreElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreElectronicoActionPerformed
        
    }//GEN-LAST:event_TxtCorreElectronicoActionPerformed

    private void TxtCorreElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreElectronicoKeyTyped
        
    
    }//GEN-LAST:event_TxtCorreElectronicoKeyTyped

    private void TxtDiasTrabajadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDiasTrabajadosKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido
             
        }
    }//GEN-LAST:event_TxtDiasTrabajadosKeyTyped

    private void TxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido
            
            
        }
    }//GEN-LAST:event_TxtTelefonoKeyTyped

    private void TxtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCelularKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido
            
            
        }
    }//GEN-LAST:event_TxtCelularKeyTyped

    private void CBoxCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBoxCargosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxCargosMouseClicked

    private void CBoxCedulasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBoxCedulasItemStateChanged
        Fila = 1;
        cargarDatos(CBoxCedulas.getSelectedItem().toString());
        BtnNuevo.setEnabled(true);
        BtnModificar.setEnabled(true);
        BtnEliminar.setEnabled(true);
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnEditar.setEnabled(true);
    }//GEN-LAST:event_CBoxCedulasItemStateChanged

    private void CBoxCedulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxCedulasActionPerformed
        
    }//GEN-LAST:event_CBoxCedulasActionPerformed

    private void TxtAuxTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAuxTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuxTransporteKeyTyped

    private void TxtAuxTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAuxTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuxTransporteActionPerformed

    public boolean isEmail(String correo) {
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
        mat = pat.matcher(correo);
        if (mat.find()) {
            System.out.println("[" + mat.group() + "]");
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane,"Correo incorrecto"); 
            return false;
            
        }
    }
    private void cargarDatos(String Cedula){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.buscar(Cedula);
            TxtCedula.setText(Empleados[0].getCedula());
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtDireccion.setText(Empleados[0].getDireccion());
            TxtCorreElectronico.setText(Empleados[0].getCorreoElectronico());
            TxtTelefono.setText(Empleados[0].getTelefono());
            TxtCelular.setText(Empleados[0].getCelular());
            TxtSalario.setText(String.valueOf((Empleados[0].getSalarioDia())));
            TxtFechaIngreso.setText(Empleados[0].getFechaIngreso());
            TxtFechaSalida.setText(Empleados[0].getFechaSalida());
            CboTipoSalario.setSelectedItem(Empleados[0].getTipoSalario());
            TxtFechaNacimiento.setText(Empleados[0].getFechaNac());
            CboEstadoCivil.setSelectedItem(Empleados[0].getEstCivil());
            CboEstadoCivil.setSelectedItem(Empleados[0].getEstCivil());
            CBoxCargos.setSelectedItem(Empleados[0].getCargo());
            CboEstado.setSelectedItem(Empleados[0].getEstado());
            TxtDiasTrabajados.setText(String.valueOf(Empleados[0].getDiasTrabajados()));
            TxtCuentaBancaria.setText(Empleados[0].getCuentaBanc());
            TxtAuxTransporte.setText(String.valueOf((Empleados[0].getAuxTransporte())));
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }

   
private void ExtraerDatos(int Fila){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.SelectAll(Fila);
           NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            TxtCedula.setText(Empleados[0].getCedula());
            CBoxCedulas.setSelectedItem(Empleados[0].getCedula());
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtDireccion.setText(Empleados[0].getDireccion());
            TxtCorreElectronico.setText(Empleados[0].getCorreoElectronico());
            TxtTelefono.setText(Empleados[0].getTelefono());
            TxtCelular.setText(Empleados[0].getCelular());
            TxtSalario.setText(String.valueOf(Empleados[0].getSalarioDia()));
            TxtFechaIngreso.setText(Empleados[0].getFechaIngreso());
            TxtFechaSalida.setText(Empleados[0].getFechaSalida());
            CboTipoSalario.setSelectedItem(Empleados[0].getTipoSalario());
            TxtFechaNacimiento.setText(Empleados[0].getFechaNac());
            CboEstadoCivil.setSelectedItem(Empleados[0].getEstCivil());
            CBoxCargos.setSelectedItem(Empleados[0].getCargo());
            CboEstado.setSelectedItem(Empleados[0].getEstado());
            TxtDiasTrabajados.setText(String.valueOf( Empleados[0].getDiasTrabajados()));
            TxtCuentaBancaria.setText(Empleados[0].getCuentaBanc());
            TxtAuxTransporte.setText(String.valueOf(Empleados[0].getAuxTransporte()));
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }
    




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnDeshacer;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnPrimero;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSiguiiente;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JComboBox CBoxCargos;
    private javax.swing.JComboBox CBoxCedulas;
    private javax.swing.JComboBox CboEstado;
    private javax.swing.JComboBox CboEstadoCivil;
    private javax.swing.JComboBox CboTipoSalario;
    private javax.swing.JTextField TxtAuxTransporte;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtCelular;
    private javax.swing.JTextField TxtCorreElectronico;
    private javax.swing.JTextField TxtCuentaBancaria;
    private javax.swing.JTextField TxtDiasTrabajados;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtFechaIngreso;
    private javax.swing.JTextField TxtFechaNacimiento;
    private javax.swing.JTextField TxtFechaSalida;
    private javax.swing.JTextField TxtPrimerApellido;
    private javax.swing.JTextField TxtPrimerNombre;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JTextField TxtSegundoApellido;
    private javax.swing.JTextField TxtSegundoNombre;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
