
package nomina.Formularios;

import com.sun.rowset.internal.Row;
import java.awt.Button;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import nomina.Clases.ClsLiquidacionNomina;
import nomina.Clases.ClsConexionDatos;
import nomina.Clases.ClsEmpleados;

/**
 *
 * @author  Wilson  Otalvaro Bedoya
 *          Victor Higuita 
 *          Juliana Toro
 */
public class FrmLiquidacion extends javax.swing.JInternalFrame {

    
    ClsConexionDatos datos = new ClsConexionDatos();
    ClsEmpleados emp = new ClsEmpleados();
    ClsLiquidacionNomina liquidacion= new ClsLiquidacionNomina();
    ResultSet rs;
    ClsEmpleados p;
    int fila=0;
    int Fila = 1;
    int Max = 1;
    String Cargo = "";
    public FrmLiquidacion() {
        initComponents();
        this.setSize(1345, 650);
        this.setVisible(true);       
        //BtnGrabar.setVisible(false);
        inhabilitar();
        
        Fila = 1;
        ExtraerDatos(Fila);  
        
        CBoxCedPrima.removeAllItems();
        CBoxCedPrima.setEnabled(true);       
        
        ArrayList List = ClsConexionDatos.LlenarCBoxCedulas();
        
        for (int i=0;i<List.size();i++){
                CBoxCedPrima.addItem(List.get(i));
        }
        
        for (int i=1;i<25;i++){
            
                CBoxPeriodo.addItem((i));
        }
    }
                   
    public void inhabilitar(){
    
    TxtPrimerApellido.setEditable(false);
    TxtSegundoApellido.setEditable(false);
    TxtPrimerNombre.setEditable(false);
    TxtSegundoNombre.setEditable(false);
    TxtSalario.setEditable(false);
    TxtAuxilioTransporte.setEditable(false);
    
    TxtSalarioBasico.setEditable(false);
    TxtValorExtras.setEditable(false);
    TxtValorExtrasN.setEditable(false);
    TxtSalarioBruto.setEditable(false);
    TxtPension.setEditable(false);
    TxtSalud.setEditable(false);
    TxtNetoaPagar.setEditable(false);
    
        
    }
    
    public void habilitar() {
        
        TxtPrimerApellido.setEnabled(true);
        TxtSegundoApellido.setEnabled(true);
        TxtPrimerNombre.setEnabled(true);
        TxtSegundoNombre.setEnabled(true);
        TxtSalario.setEnabled(true);
    }
    private void limpiar(){
        
        TxtPrimerApellido.setText("");
        TxtSegundoApellido.setText("");
        TxtPrimerNombre.setText("");
        TxtSegundoNombre.setText("");
        TxtSalario.setText("");
    }
    
    private void limpiarmov(){
        TxtSalarioBasico.setText("");
        TxtValorExtras.setText("");
        TxtValorExtrasN.setText("");
        TxtSalarioBruto.setText("");
        TxtSalud.setText("");
        TxtPension.setText("");
        TxtNetoaPagar.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtPrimerApellido = new javax.swing.JTextField();
        TxtSegundoApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtPrimerNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtAuxilioTransporte = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtPrestamos = new javax.swing.JTextField();
        TxtHorasTrabajadas = new javax.swing.JTextField();
        TxtExtrasDiurnas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtExtrasNocturnas = new javax.swing.JTextField();
        TxtSalarioBasico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TxtNetoaPagar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TxtValorExtras = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxtValorExtrasN = new javax.swing.JTextField();
        TxtSalud = new javax.swing.JTextField();
        TxtPension = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TxtSalarioBruto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TxtBonificaciones = new javax.swing.JTextField();
        BtnPrimero = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnSiguiiente = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnGrabar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        CBoxCedPrima = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CBoxPeriodo = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Liquidacion Nomina");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Periodo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 50, 20);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Primer Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 20);

        TxtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrimerApellidoActionPerformed(evt);
            }
        });
        TxtPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerApellido);
        TxtPrimerApellido.setBounds(110, 10, 120, 20);

        TxtSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSegundoApellidoActionPerformed(evt);
            }
        });
        TxtSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoApellido);
        TxtSegundoApellido.setBounds(400, 10, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Segundo Apellido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 10, 97, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Segundo Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 40, 98, 20);

        TxtSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSegundoNombreActionPerformed(evt);
            }
        });
        TxtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoNombre);
        TxtSegundoNombre.setBounds(400, 40, 120, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Primer Nombre");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 40, 85, 20);

        TxtPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrimerNombreActionPerformed(evt);
            }
        });
        TxtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerNombre);
        TxtPrimerNombre.setBounds(110, 40, 120, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Salario Dia");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 70, 70, 20);

        TxtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioActionPerformed(evt);
            }
        });
        TxtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSalarioKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSalario);
        TxtSalario.setBounds(110, 70, 110, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Bonificaciones");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 250, 100, 20);

        TxtAuxilioTransporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtAuxilioTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAuxilioTransporteActionPerformed(evt);
            }
        });
        jPanel1.add(TxtAuxilioTransporte);
        TxtAuxilioTransporte.setBounds(400, 70, 110, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 92, 660, 10);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("NETO A PAGAR:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(290, 280, 120, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("SALARIO BRUTO");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(290, 190, 100, 20);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Horas trabajadas");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 100, 100, 20);

        TxtPrestamos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrestamosActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPrestamos);
        TxtPrestamos.setBounds(400, 250, 110, 20);

        TxtHorasTrabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHorasTrabajadasActionPerformed(evt);
            }
        });
        jPanel1.add(TxtHorasTrabajadas);
        TxtHorasTrabajadas.setBounds(110, 100, 110, 20);

        TxtExtrasDiurnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtExtrasDiurnasActionPerformed(evt);
            }
        });
        jPanel1.add(TxtExtrasDiurnas);
        TxtExtrasDiurnas.setBounds(110, 130, 110, 20);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Deduccion Pension");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(290, 220, 108, 20);

        TxtExtrasNocturnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtExtrasNocturnasActionPerformed(evt);
            }
        });
        jPanel1.add(TxtExtrasNocturnas);
        TxtExtrasNocturnas.setBounds(110, 160, 110, 20);

        TxtSalarioBasico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtSalarioBasico.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtSalarioBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioBasicoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSalarioBasico);
        TxtSalarioBasico.setBounds(400, 100, 110, 21);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Auxilio Transporte");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(290, 70, 100, 20);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Salario Basico");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(290, 100, 100, 20);

        TxtNetoaPagar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxtNetoaPagar.setForeground(new java.awt.Color(255, 0, 0));
        TxtNetoaPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtNetoaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNetoaPagarActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNetoaPagar);
        TxtNetoaPagar.setBounds(400, 280, 110, 28);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Extras Diurnas");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 130, 100, 20);

        TxtValorExtras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtValorExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorExtrasActionPerformed(evt);
            }
        });
        jPanel1.add(TxtValorExtras);
        TxtValorExtras.setBounds(400, 130, 110, 20);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Valor extras D");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(290, 130, 100, 20);

        TxtValorExtrasN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtValorExtrasN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorExtrasNActionPerformed(evt);
            }
        });
        jPanel1.add(TxtValorExtrasN);
        TxtValorExtrasN.setBounds(400, 160, 110, 20);

        TxtSalud.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSaludActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSalud);
        TxtSalud.setBounds(110, 220, 110, 20);

        TxtPension.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtPension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPensionActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPension);
        TxtPension.setBounds(400, 220, 110, 20);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Extras Nocturnas");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(10, 160, 100, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Deduccion Salud");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 220, 100, 20);

        TxtSalarioBruto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtSalarioBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioBrutoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtSalarioBruto);
        TxtSalarioBruto.setBounds(400, 190, 110, 20);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Valor extras N");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(290, 160, 100, 20);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Prestamos");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(290, 250, 100, 20);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Prestamos");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(290, 250, 100, 20);

        TxtBonificaciones.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtBonificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBonificacionesActionPerformed(evt);
            }
        });
        jPanel1.add(TxtBonificaciones);
        TxtBonificaciones.setBounds(110, 250, 110, 20);

        jTabbedPane1.addTab("Datos Personales", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(40, 70, 660, 370);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Datos Personales");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        BtnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Primero.jpg"))); // NOI18N
        BtnPrimero.setText("Primero");
        BtnPrimero.setToolTipText("Primer Registro");
        BtnPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPrimero.setName(""); // NOI18N
        BtnPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrimero);
        BtnPrimero.setBounds(70, 460, 90, 60);

        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Anterior.jpg"))); // NOI18N
        BtnAnterior.setText("Anterior");
        BtnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAnterior);
        BtnAnterior.setBounds(190, 460, 90, 60);

        BtnSiguiiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Siguiente.jpg"))); // NOI18N
        BtnSiguiiente.setText("Siguiente");
        BtnSiguiiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSiguiiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSiguiiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguiienteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSiguiiente);
        BtnSiguiiente.setBounds(320, 460, 90, 60);

        BtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Ultimo.jpg"))); // NOI18N
        BtnUltimo.setText("Ultimo");
        BtnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUltimo);
        BtnUltimo.setBounds(440, 460, 90, 60);

        BtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Grabar.jpg"))); // NOI18N
        BtnGrabar.setText("Grabar");
        BtnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGrabar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGrabar);
        BtnGrabar.setBounds(820, 170, 90, 60);

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Salir.jpg"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(760, 460, 90, 60);

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/buscarlupa.jpg"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(610, 460, 90, 60);

        BtnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/calc.gif"))); // NOI18N
        BtnCalcular.setText("Calcular");
        BtnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCalcular.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCalcular);
        BtnCalcular.setBounds(820, 70, 90, 80);

        CBoxCedPrima.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBoxCedPrimaItemStateChanged(evt);
            }
        });
        CBoxCedPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxCedPrimaActionPerformed(evt);
            }
        });
        getContentPane().add(CBoxCedPrima);
        CBoxCedPrima.setBounds(360, 30, 140, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Cedula");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 30, 50, 20);

        CBoxPeriodo.setToolTipText("");
        CBoxPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBoxPeriodoItemStateChanged(evt);
            }
        });
        CBoxPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(CBoxPeriodo);
        CBoxPeriodo.setBounds(100, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeroActionPerformed
         Fila = 1;
        ExtraerDatos(Fila);
        limpiarmov();
    }//GEN-LAST:event_BtnPrimeroActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed
        
        
        int numFilas = 0;

                try {
                    liquidacion = new ClsLiquidacionNomina();
                    liquidacion.setCedula((String) CBoxCedPrima.getSelectedItem());
                    liquidacion.setPeriodo((int) CBoxPeriodo.getSelectedItem());
                    liquidacion.setSalhora(Double.parseDouble(TxtSalario.getText()));
                    liquidacion.setAuxTransporte(Double.parseDouble(TxtAuxilioTransporte.getText()));
                    liquidacion.setSalarioBasico(Double.parseDouble(TxtSalarioBasico.getText()));
                    liquidacion.setValorExtrasDiurnas(Double.parseDouble(TxtValorExtras.getText()));
                    liquidacion.setValorExtrasNocturnas(Double.parseDouble(TxtValorExtrasN.getText()));
                    liquidacion.setSalarioBruto(Double.parseDouble(TxtSalarioBruto.getText()));
                    liquidacion.setAporteSalud(Double.parseDouble(TxtSalud.getText()));
                    liquidacion.setAportePension(Double.parseDouble(TxtPension.getText()));
                    liquidacion.setBonificaciones(Double.parseDouble(TxtBonificaciones.getText()));
                    liquidacion.setPrestamos(Double.parseDouble(TxtPrestamos.getText()));
                    liquidacion.setSalarioNeto(Double.parseDouble(TxtNetoaPagar.getText()));
                    
                    
                    
                    numFilas = datos.InsertLiq(liquidacion.getCedula(),
                            liquidacion.getPeriodo(),
                            liquidacion.getSalhora(),
                            liquidacion.getAuxTransporte(),
                            liquidacion.getSalarioBasico(),
                            liquidacion.getValorExtrasDiurnas(),
                            liquidacion.getValorExtrasNocturnas(),
                            liquidacion.getSalarioBruto(),
                            liquidacion.getAporteSalud(),
                            liquidacion.getAportePension(),
                            liquidacion.getBonificaciones(),
                            liquidacion.getPrestamos(),
                            liquidacion.getSalarioNeto()
                            
                            
                            );
                    JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " Registros Guardados !!!");

                } catch (Exception ee) {
                    System.out.println(ee.getStackTrace());
                    JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " error !!!");
                }
        
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnGrabar.setEnabled(false);
        BtnBuscar.setEnabled(true);        
        inhabilitar();
    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void BtnSiguiienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguiienteActionPerformed
        Max = ClsConexionDatos.NumeroFilas();
        if (Fila < Max){
            Fila++;
        }        
        ExtraerDatos(Fila); 
        limpiarmov();
    }//GEN-LAST:event_BtnSiguiienteActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
         if (Fila > 1){
            Fila--;
        }        
        ExtraerDatos(Fila);
        limpiarmov();
        limpiarmov();
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
       Max = ClsConexionDatos.NumeroFilas();
        Fila = Max;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        int x=0;
        if(TxtPrimerApellido.getText().length()!=0){
            x=1;
        }
        else
        {
            x=2;
        }
       
        if (x==1){
        
        limpiar();
        
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        BtnGrabar.setEnabled(false);
         
        }
         if(x==2){

             Fila = 1;
        
        cargarDatos((String) CBoxCedPrima.getSelectedItem());
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        TxtAuxilioTransporte.setEnabled(true);
        TxtSalarioBasico.setEnabled(true);
        TxtValorExtras.setEnabled(true);
        TxtValorExtrasN.setEnabled(true);
        TxtSalud.setEnabled(true);
        TxtPension.setEnabled(true);
        TxtNetoaPagar.setEnabled(true);
        
                
       }
        
       
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TxtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSalarioKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSalarioKeyTyped

    private void TxtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioActionPerformed

    }//GEN-LAST:event_TxtSalarioActionPerformed

    private void TxtPrimerNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtPrimerNombreKeyTyped

    private void TxtSegundoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSegundoNombreKeyTyped

    private void TxtSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSegundoApellidoKeyTyped

    private void TxtPrimerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtPrimerApellidoKeyTyped

    private void TxtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrimerApellidoActionPerformed

    private void TxtAuxilioTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAuxilioTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAuxilioTransporteActionPerformed

    private void TxtPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrestamosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrestamosActionPerformed

    private void TxtHorasTrabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHorasTrabajadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHorasTrabajadasActionPerformed

    private void TxtExtrasDiurnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtExtrasDiurnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtExtrasDiurnasActionPerformed

    private void TxtExtrasNocturnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtExtrasNocturnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtExtrasNocturnasActionPerformed

    private void TxtSalarioBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalarioBasicoActionPerformed

    private void TxtNetoaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNetoaPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNetoaPagarActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed

        NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
        int a =0;
        int dias=0;
        
        
        if(TxtHorasTrabajadas.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar las horas Trabajadas"); 
            TxtHorasTrabajadas.requestFocus();
            return;          
        }
        if(Integer.parseInt(TxtHorasTrabajadas.getText()) > 120){
            JOptionPane.showMessageDialog(rootPane,"El Valor de las horas no debe ser mayor a 120 horas"); 
            TxtHorasTrabajadas.requestFocus();
            return;          
        }
        else
        {
            a=(Integer.parseInt(TxtHorasTrabajadas.getText()));
            dias =a/8;
        }
        if(TxtExtrasDiurnas.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar las horas  Extras Diurnas"); 
            TxtExtrasDiurnas.requestFocus();
            return;          
        }
        if(TxtExtrasNocturnas.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar las horas  Extras Nocturnas"); 
            TxtExtrasNocturnas.requestFocus();
            return;          
        }
        if(Integer.parseInt(TxtExtrasDiurnas.getText()) > 120){
            JOptionPane.showMessageDialog(rootPane,"El Valor de las horas Extras no debe ser mayor a 120 horas"); 
            TxtExtrasDiurnas.requestFocus();
            return;          
        }
        if(TxtPrestamos.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar el valor del prestamo"); 
            TxtPrestamos.requestFocus();
            return;          
        }
        if(TxtBonificaciones.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar el valor de las bonificaciones"); 
            TxtBonificaciones.requestFocus();
            return;          
        }
        ClsLiquidacionNomina  c = new ClsLiquidacionNomina();
        double salBruto = c.SalarioBasico(dias,Double.parseDouble(TxtSalario.getText()));
        String SalarioB = (String.valueOf(salBruto));
        TxtSalarioBasico.setText(SalarioB);

        double VExtraDiurna = c.ValHorasExtras(Integer.parseInt(TxtExtrasDiurnas.getText()),Double.parseDouble(TxtSalario.getText()));
        String ValorExtraD = (String.valueOf(VExtraDiurna));
        TxtValorExtras.setText(ValorExtraD);
        /*
         
         */
        double VExtraNocturna = c.ValHorasExtrasN(Integer.parseInt(TxtExtrasNocturnas.getText()),Double.parseDouble(TxtSalario.getText()));
        String ValorExtraN = (String.valueOf(VExtraNocturna));
        TxtValorExtrasN.setText(ValorExtraN);
                
        //calculo salario bruto
        double SalarioBruto = c.SalarioBruto( (salBruto),(VExtraDiurna),(VExtraNocturna) );
        String ValorSalarioBruto=(String.valueOf(SalarioBruto));
        TxtSalarioBruto.setText(ValorSalarioBruto);
        
        double Salud = c.CalcAporteSalud(SalarioBruto);
        String ValorSalud = (String.valueOf(Salud));
        TxtSalud.setText(ValorSalud);
        
        double Pension = c.CalcAporteSalud(SalarioBruto);
        String ValorPension = (String.valueOf(Pension));
        TxtPension.setText(ValorPension);
        
        double NetoPagar = c.CalcSalarioNeto( SalarioBruto, Pension, Salud, Double.parseDouble(TxtPrestamos.getText()),  
                Double.parseDouble(TxtAuxilioTransporte.getText()),  Double.parseDouble(TxtBonificaciones.getText()), 
                Double.parseDouble(TxtExtrasDiurnas.getText()), Double.parseDouble(TxtExtrasNocturnas.getText()));
        String ValNetoPagar = (String.valueOf(NetoPagar));
        TxtNetoaPagar.setText(ValNetoPagar);
        
        
        
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void TxtValorExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorExtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorExtrasActionPerformed

    private void TxtValorExtrasNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorExtrasNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorExtrasNActionPerformed

    private void TxtSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSegundoApellidoActionPerformed

    private void TxtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrimerNombreActionPerformed

    private void TxtSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSegundoNombreActionPerformed

    private void TxtSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSaludActionPerformed

    private void TxtPensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPensionActionPerformed

    private void TxtSalarioBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSalarioBrutoActionPerformed

    private void TxtBonificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBonificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBonificacionesActionPerformed

    private void CBoxCedPrimaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBoxCedPrimaItemStateChanged

        limpiar();
        BtnCalcular.setEnabled(true);
        cargarDatos(CBoxCedPrima.getSelectedItem().toString());
        /*
        if (CBoxCedPrima.getSelectedItem().toString().length() != 0){
            NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            ClsPrimaDeServicios  c = new ClsPrimaDeServicios();
            double Prima = c.CalcPrima(Double.parseDouble(TxtSalario.getText()),(TxtFechaIngreso.getText()));
            String PrimaS = Format.format(Prima);
            TxtValorPrima.setText(PrimaS);
        }*/
    }//GEN-LAST:event_CBoxCedPrimaItemStateChanged

    private void CBoxCedPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxCedPrimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxCedPrimaActionPerformed

    private void CBoxPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBoxPeriodoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxPeriodoItemStateChanged

    private void CBoxPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxPeriodoActionPerformed

    
    private void cargarDatos(String Cedula){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.buscar(Cedula);
            //TxtCedula.setText(Empleados[0].getCedula());
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtSalario.setText(String.valueOf(Empleados[0].getSalarioDia()));
            TxtAuxilioTransporte.setText(String.valueOf(Empleados[0].getAuxTransporte()));
            
           
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }

   
private void ExtraerDatos(int Fila){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.SelectAll(Fila);
           NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            //TxtCedula.setText(Empleados[0].getCedula());
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtSalario.setText(String.valueOf(Empleados[0].getSalarioDia()));
            TxtAuxilioTransporte.setText(String.valueOf(Empleados[0].getAuxTransporte()));
            CBoxCedPrima.setSelectedItem(Empleados[0].getCedula());
           
            
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }
    




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JButton BtnPrimero;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSiguiiente;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JComboBox CBoxCedPrima;
    private javax.swing.JComboBox CBoxPeriodo;
    private javax.swing.JTextField TxtAuxilioTransporte;
    private javax.swing.JTextField TxtBonificaciones;
    private javax.swing.JTextField TxtExtrasDiurnas;
    private javax.swing.JTextField TxtExtrasNocturnas;
    private javax.swing.JTextField TxtHorasTrabajadas;
    private javax.swing.JTextField TxtNetoaPagar;
    private javax.swing.JTextField TxtPension;
    private javax.swing.JTextField TxtPrestamos;
    private javax.swing.JTextField TxtPrimerApellido;
    private javax.swing.JTextField TxtPrimerNombre;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JTextField TxtSalarioBasico;
    private javax.swing.JTextField TxtSalarioBruto;
    private javax.swing.JTextField TxtSalud;
    private javax.swing.JTextField TxtSegundoApellido;
    private javax.swing.JTextField TxtSegundoNombre;
    private javax.swing.JTextField TxtValorExtras;
    private javax.swing.JTextField TxtValorExtrasN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
