
package nomina.Formularios;

import com.sun.rowset.internal.Row;
import java.awt.Button;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.Format;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import nomina.Clases.ClsCalculos;
import nomina.Clases.ClsConexionDatos;
import nomina.Clases.ClsEmpleados;
import nomina.Clases.ClsPrimaDeServicios;


/**
 *
 * @author  Wilson  Otalvaro Bedoya
 *          Victor Higuita 
 *          Juliana Toro
 */
public class FrmPrima extends javax.swing.JInternalFrame {

    ClsConexionDatos datos = new ClsConexionDatos();
    ClsEmpleados emp = new ClsEmpleados();
    ResultSet rs;
    ClsEmpleados p;
    int fila=0;
    int Fila = 1;
    int Max = 1;
    
    
    public FrmPrima() {
        initComponents();
        this.setSize(1345, 650);
        this.setVisible(true);       
        BtnCalcular.setEnabled(true);
        CBoxCedPrima.setEnabled(true);
        CBoxCedPrima.setVisible(true);
        inhabilitar();  
        Fila = 1;
        ExtraerDatos(Fila);
        //Ojo
        CBoxCedPrima.removeAllItems();
        CBoxCedPrima.setEnabled(true);       
        
        ArrayList List = ClsConexionDatos.LlenarCBoxCedulas();
        
        for (int i=0;i<List.size();i++){
                CBoxCedPrima.addItem(List.get(i));
        }
    }
                   
    public void inhabilitar(){
    
    TxtPrimerApellido.setEditable(false);
    TxtSegundoApellido.setEditable(false);
    TxtPrimerNombre.setEditable(false);
    TxtSegundoNombre.setEditable(false);
    TxtFechaIngreso.setEditable(false);
    TxtValorPrima.setEditable(false);
    TxtSalario.setEditable(false);
    
    }
    
    public void habilitar() {
        
        TxtPrimerApellido.setEnabled(true);
        TxtSegundoApellido.setEnabled(true);
        TxtPrimerNombre.setEnabled(true);
        TxtSegundoNombre.setEnabled(true);
        TxtFechaIngreso.setEnabled(true);
        TxtValorPrima.setEnabled(true);
        TxtSalario.setEnabled(true);

    }
    private void limpiar(){
    
    TxtPrimerApellido.setText("");
    TxtSegundoApellido.setText("");
    TxtPrimerNombre.setText("");
    TxtSegundoNombre.setText("");
    TxtFechaIngreso.setText("");
    TxtValorPrima.setText("");
    TxtSalario.setText("");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCalcular = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtPrimerApellido = new javax.swing.JTextField();
        TxtSegundoApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtPrimerNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtFechaIngreso = new javax.swing.JTextField();
        TxtValorPrima = new javax.swing.JTextField();
        jSalario = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        CBoxCedPrima = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Prima");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 50, 20);

        BtnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/calc.gif"))); // NOI18N
        BtnCalcular.setText("Calcular");
        BtnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCalcular.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCalcular);
        BtnCalcular.setBounds(740, 160, 90, 80);

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Salir.jpg"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(740, 280, 90, 60);

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/buscarlupa.jpg"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(740, 80, 90, 60);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Primer Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 90, 20);

        TxtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrimerApellidoActionPerformed(evt);
            }
        });
        TxtPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerApellido);
        TxtPrimerApellido.setBounds(100, 30, 120, 20);

        TxtSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoApellido);
        TxtSegundoApellido.setBounds(400, 30, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Segundo Apellido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 30, 97, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Segundo Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 70, 98, 20);

        TxtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoNombre);
        TxtSegundoNombre.setBounds(400, 70, 120, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Primer Nombre");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 85, 20);

        TxtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerNombre);
        TxtPrimerNombre.setBounds(100, 70, 120, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Fecha Ingreso");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 110, 100, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Valor Prima");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 160, 110, 30);
        jPanel1.add(TxtFechaIngreso);
        TxtFechaIngreso.setBounds(100, 110, 120, 20);

        TxtValorPrima.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxtValorPrima.setForeground(new java.awt.Color(255, 0, 0));
        TxtValorPrima.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TxtValorPrima);
        TxtValorPrima.setBounds(110, 160, 160, 30);

        jSalario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jSalario.setText("Salario");
        jPanel1.add(jSalario);
        jSalario.setBounds(290, 110, 100, 20);

        TxtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(TxtSalario);
        TxtSalario.setBounds(400, 110, 110, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 140, 650, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 60, 650, 370);

        CBoxCedPrima.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBoxCedPrimaItemStateChanged(evt);
            }
        });
        CBoxCedPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxCedPrimaActionPerformed(evt);
            }
        });
        getContentPane().add(CBoxCedPrima);
        CBoxCedPrima.setBounds(120, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
        
        if (CBoxCedPrima.getSelectedItem().toString().length() != 0){
            NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            ClsPrimaDeServicios  c = new ClsPrimaDeServicios();
            double Prima = c.CalcPrima(Double.parseDouble(TxtSalario.getText()),(TxtFechaIngreso.getText()));
            String PrimaS = Format.format(Prima);           
            TxtValorPrima.setText(PrimaS); 
        }
        
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void TxtPrimerNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtPrimerNombreKeyTyped

    private void TxtSegundoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSegundoNombreKeyTyped

    private void TxtSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSegundoApellidoKeyTyped

    private void TxtPrimerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtPrimerApellidoKeyTyped

    private void TxtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrimerApellidoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        int x=0;
        if(TxtPrimerApellido.getText().length()!=0){
            x=1;
        }
        else
        {
            x=2;
        }

        if (x==1){

            limpiar();
            
            BtnCalcular.setEnabled(true);
           

            
        }
        if(x==2){

            Fila = 1;
            
            

        }

    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void CBoxCedPrimaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBoxCedPrimaItemStateChanged
        

            limpiar();           
            BtnCalcular.setEnabled(true);            
            cargarDatos(CBoxCedPrima.getSelectedItem().toString());
            /*
            if (CBoxCedPrima.getSelectedItem().toString().length() != 0){
                NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
                ClsPrimaDeServicios  c = new ClsPrimaDeServicios();
                double Prima = c.CalcPrima(Double.parseDouble(TxtSalario.getText()),(TxtFechaIngreso.getText()));
                String PrimaS = Format.format(Prima);           
                TxtValorPrima.setText(PrimaS); 
            }*/       
    }//GEN-LAST:event_CBoxCedPrimaItemStateChanged

    private void CBoxCedPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxCedPrimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxCedPrimaActionPerformed

    private void cargarDatos(String Cedula){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.buscar(Cedula);            
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtFechaIngreso.setText(Empleados[0].getFechaIngreso());
            TxtSalario.setText(String.valueOf(Empleados[0].getSalarioDia()));
            
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }

   
private void ExtraerDatos(int Fila){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.SelectAll(Fila);
           NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtFechaIngreso.setText(Empleados[0].getFechaIngreso());
           
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }
    




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox CBoxCedPrima;
    private javax.swing.JTextField TxtFechaIngreso;
    private javax.swing.JTextField TxtPrimerApellido;
    private javax.swing.JTextField TxtPrimerNombre;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JTextField TxtSegundoApellido;
    private javax.swing.JTextField TxtSegundoNombre;
    private javax.swing.JTextField TxtValorPrima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSalario;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
