
package nomina.Formularios;

import com.sun.rowset.internal.Row;
import java.awt.Button;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import nomina.Clases.ClsCalculos;
import nomina.Clases.ClsConexionDatos;
import nomina.Clases.ClsEmpleados;
import java.text.NumberFormat;
import nomina.Clases.ClsCesantias;

    

/**
 *
 * @author  Wilson  Otalvaro Bedoya
 *          Victor Higuita 
 *          Juliana Toro
 */
public class FrmCesantias extends javax.swing.JInternalFrame {
    
    NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
    

    
    ClsConexionDatos datos = new ClsConexionDatos();
    ClsEmpleados emp = new ClsEmpleados();
    ResultSet rs;
    ClsEmpleados p;
    int fila=0;
    int Fila = 1;
    int Max = 1;
    
    public FrmCesantias() {
        initComponents();
        this.setSize(1345, 650);
        this.setVisible(true);       
        BtnCalcular.setEnabled(true);
        CBoxCedCesantias.setEnabled(true);
        CBoxCedCesantias.setVisible(true);
        inhabilitar();  
        Fila = 1;
        ExtraerDatos(Fila);
        //Ojo
        //Ojo
        CBoxCedCesantias.removeAllItems();
        CBoxCedCesantias.setEnabled(true);       
        
        ArrayList List = ClsConexionDatos.LlenarCBoxCedulas();
        
        for (int i=0;i<List.size();i++){
                CBoxCedCesantias.addItem(List.get(i));
        }
    }
                   
    public void inhabilitar(){
    
    TxtPrimerApellido.setEditable(false);
    TxtSegundoApellido.setEditable(false);
    TxtPrimerNombre.setEditable(false);
    TxtSegundoNombre.setEditable(false);
    TxtFechaIngreso.setEditable(false);
    TxtDiasTrabajados.setEditable(false);
    TxtSalario.setEditable(false);
    TxtValorCesantias.setEditable(false);
    
    }
    
    private void limpiar(){
    
    TxtPrimerApellido.setText("");
    TxtSegundoApellido.setText("");
    TxtPrimerNombre.setText("");
    TxtSegundoNombre.setText("");
    TxtFechaIngreso.setText("");
    TxtDiasTrabajados.setText("");
    TxtSalario.setText("");
    TxtValorCesantias.setText("");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCalcular = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtPrimerApellido = new javax.swing.JTextField();
        TxtSegundoApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtPrimerNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtFechaIngreso = new javax.swing.JTextField();
        TxtDiasTrabajados = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtSalario = new javax.swing.JTextField();
        TxtValorCesantias = new javax.swing.JTextField();
        jCalculoCesantias = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CBoxCedCesantias = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cesantias");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 50, 20);

        BtnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/calc.gif"))); // NOI18N
        BtnCalcular.setText("Calcular");
        BtnCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCalcular.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCalcular);
        BtnCalcular.setBounds(740, 170, 90, 80);

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Salir.jpg"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(740, 280, 90, 60);

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/buscarlupa.jpg"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(740, 80, 90, 60);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Primer Apellido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 90, 20);

        TxtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrimerApellidoActionPerformed(evt);
            }
        });
        TxtPrimerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerApellido);
        TxtPrimerApellido.setBounds(110, 30, 120, 20);

        TxtSegundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoApellido);
        TxtSegundoApellido.setBounds(400, 30, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Segundo Apellido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 30, 97, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Segundo Nombre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 70, 98, 20);

        TxtSegundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSegundoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSegundoNombre);
        TxtSegundoNombre.setBounds(400, 70, 120, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Primer Nombre");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 85, 20);

        TxtPrimerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrimerNombreKeyTyped(evt);
            }
        });
        jPanel1.add(TxtPrimerNombre);
        TxtPrimerNombre.setBounds(110, 70, 120, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Fecha Ingreso");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 110, 90, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Dias Trabajados");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 150, 100, 20);

        TxtFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFechaIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtFechaIngreso);
        TxtFechaIngreso.setBounds(110, 110, 120, 20);
        jPanel1.add(TxtDiasTrabajados);
        TxtDiasTrabajados.setBounds(110, 150, 120, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Salario Dia");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 110, 70, 20);

        TxtSalario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSalarioActionPerformed(evt);
            }
        });
        TxtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSalarioKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSalario);
        TxtSalario.setBounds(400, 110, 120, 20);

        TxtValorCesantias.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TxtValorCesantias.setForeground(new java.awt.Color(255, 0, 0));
        TxtValorCesantias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtValorCesantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorCesantiasActionPerformed(evt);
            }
        });
        TxtValorCesantias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtValorCesantiasKeyTyped(evt);
            }
        });
        jPanel1.add(TxtValorCesantias);
        TxtValorCesantias.setBounds(150, 200, 130, 30);

        jCalculoCesantias.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCalculoCesantias.setText("Valor Cesantías");
        jPanel1.add(jCalculoCesantias);
        jCalculoCesantias.setBounds(10, 200, 140, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 180, 650, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 80, 650, 370);

        CBoxCedCesantias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBoxCedCesantiasItemStateChanged(evt);
            }
        });
        CBoxCedCesantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxCedCesantiasActionPerformed(evt);
            }
        });
        getContentPane().add(CBoxCedCesantias);
        CBoxCedCesantias.setBounds(120, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
                
        if (CBoxCedCesantias.getSelectedItem().toString().length() != 0){
            NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            ClsCesantias  c = new ClsCesantias();
            double Cesantias = c.CalcCesantias(Double.parseDouble(TxtSalario.getText()),(Double.parseDouble(TxtDiasTrabajados.getText())));
            String PrimaS = Format.format(Cesantias);
            TxtValorCesantias.setText(PrimaS);
        }      
           
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void TxtPrimerNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtPrimerNombreKeyTyped

    private void TxtSegundoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoNombreKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSegundoNombreKeyTyped

    private void TxtSegundoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSegundoApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSegundoApellidoKeyTyped

    private void TxtPrimerApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtPrimerApellidoKeyTyped

    private void TxtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrimerApellidoActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        int x=0;
        if(TxtPrimerApellido.getText().length()!=0){
            x=1;
        }
        else
        {
            x=2;
        }

        if (x==1){

            limpiar();
            
            BtnCalcular.setEnabled(true);
           

            
        }
        if(x==2){

            Fila = 1;
            cargarDatos((String) CBoxCedCesantias.getSelectedItem());
            

        }

    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TxtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSalarioActionPerformed

    }//GEN-LAST:event_TxtSalarioActionPerformed

    private void TxtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSalarioKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtSalarioKeyTyped

    private void TxtValorCesantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorCesantiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorCesantiasActionPerformed

    private void TxtValorCesantiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtValorCesantiasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorCesantiasKeyTyped

    private void CBoxCedCesantiasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBoxCedCesantiasItemStateChanged

        limpiar();
        
        BtnCalcular.setEnabled(true);

        cargarDatos(CBoxCedCesantias.getSelectedItem().toString());
        /*
        if (CBoxCedCesantias.getSelectedItem().toString().length() != 0){
            NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            ClsCesantias  c = new ClsCesantias();
            double Cesantias = c.CalcCesantias(Double.parseDouble(TxtSalario.getText()),(Double.parseDouble(TxtDiasTrabajados.getText())));
            String PrimaS = Format.format(Cesantias);
            TxtValorCesantias.setText(PrimaS);
        }*/
    }//GEN-LAST:event_CBoxCedCesantiasItemStateChanged

    private void CBoxCedCesantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxCedCesantiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxCedCesantiasActionPerformed

    private void TxtFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFechaIngresoActionPerformed

    private void cargarDatos(String Cedula){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.buscar(Cedula);
            
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtFechaIngreso.setText(Empleados[0].getFechaIngreso());
            TxtSalario.setText(String.valueOf(Empleados[0].getSalarioDia()));
            TxtDiasTrabajados.setText(String.valueOf(Empleados[0].getDiasTrabajados()));
            
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }

   
private void ExtraerDatos(int Fila){      
        ClsEmpleados[] Empleados = new ClsEmpleados[1];
        try {            
           Empleados = ClsConexionDatos.SelectAll(Fila);
           NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            
            TxtPrimerApellido.setText(Empleados[0].getPrimerApellido());
            TxtSegundoApellido.setText(Empleados[0].getSegundoApellido());
            TxtPrimerNombre.setText(Empleados[0].getPrimerNombre());
            TxtSegundoNombre.setText(Empleados[0].getSegundoNombre());
            TxtFechaIngreso.setText(Empleados[0].getFechaIngreso());
           
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }
    




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox CBoxCedCesantias;
    private javax.swing.JTextField TxtDiasTrabajados;
    private javax.swing.JTextField TxtFechaIngreso;
    private javax.swing.JTextField TxtPrimerApellido;
    private javax.swing.JTextField TxtPrimerNombre;
    private javax.swing.JTextField TxtSalario;
    private javax.swing.JTextField TxtSegundoApellido;
    private javax.swing.JTextField TxtSegundoNombre;
    private javax.swing.JTextField TxtValorCesantias;
    private javax.swing.JLabel jCalculoCesantias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
