/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina.Formularios;

import java.util.GregorianCalendar;
import nomina.Clases.ClsCalculos;
import nomina.Clases.ClsConexionDatos;
import nomina.Clases.ClsEmpleados;
import nomina.Clases.ClsImpresora;
import nomina.Clases.ClsLiquidacionNomina;

/**
 *
 * @author Wilson
 */
public class FrmPrincipal extends javax.swing.JFrame {
    ClsImpresora P;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(int a) {
        initComponents();
       if(a==1){
           MnuUsuarios.setEnabled(false);
           
           
       } 
    if(a==2){
           MnuHerramientas.setEnabled(true);
           
       } 
    
    
    this.setSize(1370, 730);
    this.setVisible(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        MnubConceptos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MnuEmpleados = new javax.swing.JMenuItem();
        MnuConceptos = new javax.swing.JMenuItem();
        MnuCargos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnuNovedades = new javax.swing.JMenuItem();
        MnuPrima = new javax.swing.JMenuItem();
        MnuCesantias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MnuHerramientas = new javax.swing.JMenu();
        MnuUsuarios = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nomina");

        desktopPane.setBackground(new java.awt.Color(153, 153, 153));

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Empleados.jpg"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        MnubConceptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Conceptos.jpg"))); // NOI18N
        MnubConceptos.setFocusable(false);
        MnubConceptos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MnubConceptos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MnubConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnubConceptosActionPerformed(evt);
            }
        });
        jToolBar1.add(MnubConceptos);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Cargos.jpg"))); // NOI18N
        jButton2.setToolTipText("Cargos");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        desktopPane.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1300, 40);
        jToolBar1.getAccessibleContext().setAccessibleDescription("");
        jToolBar1.getAccessibleContext().setAccessibleParent(this);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivos");

        jMenu1.setText("Maestros");

        MnuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Empleados.jpg"))); // NOI18N
        MnuEmpleados.setText("Empleados");
        MnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(MnuEmpleados);

        MnuConceptos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Conceptos.jpg"))); // NOI18N
        MnuConceptos.setText("Conceptos");
        MnuConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuConceptosActionPerformed(evt);
            }
        });
        jMenu1.add(MnuConceptos);

        MnuCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Cargos.jpg"))); // NOI18N
        MnuCargos.setText("Cargos");
        MnuCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCargosActionPerformed(evt);
            }
        });
        jMenu1.add(MnuCargos);

        fileMenu.add(jMenu1);

        menuBar.add(fileMenu);

        jMenu2.setText("Procesos");

        MnuNovedades.setText("Novedades");
        MnuNovedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuNovedadesActionPerformed(evt);
            }
        });
        jMenu2.add(MnuNovedades);

        MnuPrima.setText("Prima");
        MnuPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuPrimaActionPerformed(evt);
            }
        });
        jMenu2.add(MnuPrima);

        MnuCesantias.setText("Cesantias");
        MnuCesantias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCesantiasActionPerformed(evt);
            }
        });
        jMenu2.add(MnuCesantias);

        menuBar.add(jMenu2);

        jMenu3.setText("Informes");

        jMenu5.setText("Maestros");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Empleados.jpg"))); // NOI18N
        jMenuItem6.setText("Empleados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Conceptos");
        jMenu5.add(jMenuItem7);

        jMenu3.add(jMenu5);

        menuBar.add(jMenu3);

        MnuHerramientas.setText("Herramientas");

        MnuUsuarios.setText("Usuarios");
        MnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuUsuariosActionPerformed(evt);
            }
        });
        MnuHerramientas.add(MnuUsuarios);

        menuBar.add(MnuHerramientas);

        jMenu6.setText("Utilidades");
        menuBar.add(jMenu6);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEmpleadosActionPerformed
        // TODO add your handling code here:
        
        FrmEmpleados emp = new FrmEmpleados();
        desktopPane.add(emp);
        emp.show();
    }//GEN-LAST:event_MnuEmpleadosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmEmpleados emp = new FrmEmpleados();
        desktopPane.add(emp);
        emp.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MnuConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuConceptosActionPerformed
        
        FrmConceptos con = new FrmConceptos();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnuConceptosActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmImpresionTxt con = new FrmImpresionTxt();
        desktopPane.add(con);
        con.show();        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void MnuCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCargosActionPerformed
            FrmCargos con = new FrmCargos();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnuCargosActionPerformed

    private void MnubConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnubConceptosActionPerformed
        // TODO add your handling code here:
         FrmConceptos con = new FrmConceptos();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnubConceptosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmCargos con = new FrmCargos();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuUsuariosActionPerformed
        FrmUsuariosCrear con = new FrmUsuariosCrear();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnuUsuariosActionPerformed

    private void MnuCesantiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCesantiasActionPerformed
       FrmCesantias con = new FrmCesantias();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnuCesantiasActionPerformed

    private void MnuPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuPrimaActionPerformed
        FrmPrima con = new FrmPrima();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnuPrimaActionPerformed

    private void MnuNovedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuNovedadesActionPerformed
        FrmLiquidacion con = new FrmLiquidacion();
        desktopPane.add(con);
        con.show();
    }//GEN-LAST:event_MnuNovedadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                int a=0;
                new FrmPrincipal(a).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuCargos;
    private javax.swing.JMenuItem MnuCesantias;
    private javax.swing.JMenuItem MnuConceptos;
    private javax.swing.JMenuItem MnuEmpleados;
    private javax.swing.JMenu MnuHerramientas;
    private javax.swing.JMenuItem MnuNovedades;
    private javax.swing.JMenuItem MnuPrima;
    private javax.swing.JMenuItem MnuUsuarios;
    private javax.swing.JButton MnubConceptos;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
