/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina.Formularios;

import com.sun.rowset.internal.Row;
import java.awt.Button;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import nomina.Clases.ClsConUsuarios;
import nomina.Clases.ClsUsuarios;
/**
 *
 * @author Wilson
 */
public class Frmusuarios extends javax.swing.JFrame {

    ClsConUsuarios datos = new ClsConUsuarios();
    ClsUsuarios usu = new ClsUsuarios();
    ResultSet rs;
    ClsUsuarios p;
    int fila=0;
    int Fila = 1;
    int Max = 1;
    /**
     * Creates new form FrmLiquidacion
     */
    public Frmusuarios() {
        initComponents();
        this.setSize(1345, 650);
        BtnGrabar.setEnabled(false);
        BtnDeshacer.setEnabled(false);
        inhabilitar();
        BtnModificar.setVisible(false);        
        Fila = 1;
        ExtraerDatos(Fila);                         
    }
public void inhabilitar(){
    TxtCedula.setEnabled(false);
    TxtUsuario.setEnabled(false);
    TxtContraseña.setEnabled(false);
    TxtApellidos.setEnabled(false);
    CboTipoUsuario.setEnabled(false);
    
    }
    
    public void habilitar() {
        TxtCedula.setEnabled(true);
        TxtUsuario.setEnabled(true);
        TxtContraseña.setEnabled(true);
        TxtApellidos.setEnabled(true);
        CboTipoUsuario.setEnabled(true);
        
    }
    private void limpiar(){
        TxtCedula.setText("");
        TxtUsuario.setText("");
        TxtContraseña.setText("");
        TxtApellidos.setText("");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        TxtContraseña = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtApellidos = new javax.swing.JTextField();
        CboTipoUsuario = new javax.swing.JComboBox();
        BtnPrimero = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        BtnSiguiiente = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnGrabar = new javax.swing.JButton();
        BtnDeshacer = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 50, 20);

        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCedulaActionPerformed(evt);
            }
        });
        TxtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(TxtCedula);
        TxtCedula.setBounds(120, 30, 120, 20);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 90, 20);

        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(TxtUsuario);
        TxtUsuario.setBounds(120, 30, 270, 20);

        TxtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtContraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(TxtContraseña);
        TxtContraseña.setBounds(120, 110, 120, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 65, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Tipo Usuario");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 71, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Apellidos");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 51, 20);

        TxtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidosKeyTyped(evt);
            }
        });
        jPanel1.add(TxtApellidos);
        TxtApellidos.setBounds(120, 70, 270, 20);

        CboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administador", "Usuario" }));
        jPanel1.add(CboTipoUsuario);
        CboTipoUsuario.setBounds(120, 150, 110, 20);

        jTabbedPane1.addTab("Datos ", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(40, 70, 660, 370);

        BtnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Primero.jpg"))); // NOI18N
        BtnPrimero.setText("Primero");
        BtnPrimero.setToolTipText("Primer Registro");
        BtnPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPrimero.setName(""); // NOI18N
        BtnPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPrimero);
        BtnPrimero.setBounds(70, 460, 90, 60);

        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Anterior.jpg"))); // NOI18N
        BtnAnterior.setText("Anterior");
        BtnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAnterior);
        BtnAnterior.setBounds(190, 460, 90, 60);

        BtnSiguiiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Siguiente.jpg"))); // NOI18N
        BtnSiguiiente.setText("Siguiente");
        BtnSiguiiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSiguiiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSiguiiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguiienteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSiguiiente);
        BtnSiguiiente.setBounds(320, 460, 90, 60);

        BtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Ultimo.jpg"))); // NOI18N
        BtnUltimo.setText("Ultimo");
        BtnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUltimo);
        BtnUltimo.setBounds(440, 460, 90, 60);

        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Editar.jpg"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEditar);
        BtnEditar.setBounds(760, 170, 90, 60);

        BtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Grabar.jpg"))); // NOI18N
        BtnGrabar.setText("Grabar");
        BtnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGrabar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGrabar);
        BtnGrabar.setBounds(760, 240, 90, 60);

        BtnDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Deshacer1.jpg"))); // NOI18N
        BtnDeshacer.setText("Deshacer");
        BtnDeshacer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnDeshacer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnDeshacer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeshacerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDeshacer);
        BtnDeshacer.setBounds(760, 310, 90, 60);

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Salir.jpg"))); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir);
        BtnSalir.setBounds(760, 460, 90, 60);

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/05.jpg"))); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNuevo);
        BtnNuevo.setBounds(760, 100, 90, 60);

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Deshacer.jpg"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnEliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminar);
        BtnEliminar.setBounds(760, 380, 90, 60);

        BtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/Modificar.jpg"))); // NOI18N
        BtnModificar.setText("Modificar");
        BtnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnModificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModificar);
        BtnModificar.setBounds(760, 240, 90, 60);

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nomina/Iconos/buscarlupa.jpg"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBuscar);
        BtnBuscar.setBounds(610, 460, 90, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void TxtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCedulaActionPerformed

    }//GEN-LAST:event_TxtCedulaActionPerformed

    private void TxtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCedulaKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo numeros");
            getToolkit().beep(); //sonido

        }
        if(tecla==KeyEvent.VK_ENTER){
            try
            {

                datos.buscarEmpleado(TxtCedula.getText());
                TxtCedula.requestFocus();
            }
            catch (Exception e)
            {

            }
            //setVisible(false);
        }
    }//GEN-LAST:event_TxtCedulaKeyTyped

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void TxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtUsuarioKeyTyped

    private void TxtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtContraseñaKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtContraseñaKeyTyped

    private void TxtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidosKeyTyped
        char tecla;
        tecla= evt.getKeyChar();
        if(!Character.isLetter(tecla)&&tecla!=KeyEvent.VK_ESCAPE&&tecla!=KeyEvent.VK_BACK_SPACE){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Debe Ingresar solo letras");
            getToolkit().beep(); //sonido

        }
    }//GEN-LAST:event_TxtApellidosKeyTyped

    private void BtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeroActionPerformed
        Fila = 1;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnPrimeroActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        if (Fila > 1){
            Fila--;
        }
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void BtnSiguiienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguiienteActionPerformed
        Max = ClsConUsuarios.NumeroFilas();
        if (Fila < Max){
            Fila++;
        }
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnSiguiienteActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
        Max = ClsConUsuarios.NumeroFilas();
        Fila = Max;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        BtnNuevo.setEnabled(false);
        BtnDeshacer.setEnabled(true);
        BtnGrabar.setVisible(false);
        BtnEliminar.setEnabled(false);
        BtnModificar.setVisible(true);
        BtnEditar.setEnabled(false);
        habilitar();

    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed

        char tecla=0;
        String cedula="";
        if(TxtCedula.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar cedula");
            TxtCedula.requestFocus();
            return;
        }

        if (TxtCedula.getText().length() != 0) {
            try {

                if (datos.selectEmpleado(TxtCedula.getText()) == 1) {
                    JOptionPane.showMessageDialog(null, "Usuario ya existe: " + TxtCedula.getText());
                    TxtCedula.requestFocus();
                    return;
                }
            } catch (Exception e) {
            }
            //setVisible(false);
        }

        if(TxtUsuario.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar El Usuario");
            TxtUsuario.requestFocus();
            return;
        }
        if(TxtApellidos.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar el Apellido del Usuario");
            TxtApellidos.requestFocus();
            return;
        }
        if(TxtContraseña.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane,"Debe digitar la  Contraseña del Usuario");
            TxtContraseña.requestFocus();
            return;
        }
//        if(TxtTipoUsuario.getText().length() == 0){
//            JOptionPane.showMessageDialog(rootPane,"Debe digitar el tipo de Usuario");
//            TxtTipoUsuario.requestFocus();
//            return;
//        }
        {
            int numFilas = 0;

            try {
                usu = new ClsUsuarios();
                usu.setCedula(TxtCedula.getText());
                usu.setNombre(TxtUsuario.getText());
                usu.setApellidos(TxtApellidos.getText());
                usu.setContraseña(TxtContraseña.getText());
                usu.setTipoUsuario(CboTipoUsuario.getSelectedItem().toString());

                numFilas = datos.Insert(
                    usu.getCedula(),
                    usu.getNombre(),
                    usu.getApellidos(),
                    usu.getContraseña(),
                    usu.getTipoUsuario()

                );
                JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " Registros Guardados !!!");

            } catch (Exception ee) {
                System.out.println(ee.getStackTrace());
                JOptionPane.showMessageDialog(null, String.valueOf(numFilas) + " error !!!");
            }
        }
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnGrabar.setEnabled(false);
        BtnNuevo.setEnabled(true);
        BtnEditar.setEnabled(true);
        BtnBuscar.setEnabled(true);
        inhabilitar();
    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void BtnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeshacerActionPerformed
        // TODO add your handling code here:
        BtnNuevo.setEnabled(true);
        BtnGrabar.setVisible(true);
        BtnGrabar.setEnabled(false);
        BtnDeshacer.setEnabled(false);
        BtnEditar.setEnabled(true);
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        limpiar();
        Fila = 1;
        ExtraerDatos(Fila);
        inhabilitar();
        BtnEliminar.setEnabled(true);
        BtnModificar.setVisible(false);
        BtnBuscar.setEnabled(true);

    }//GEN-LAST:event_BtnDeshacerActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);

    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        // TODO add your handling code here:
        BtnGrabar.setEnabled(true);
        BtnDeshacer.setEnabled(true);
        BtnEditar.setEnabled(false);
        BtnNuevo.setEnabled(false);
        BtnPrimero.setEnabled(false);
        BtnAnterior.setEnabled(false);
        BtnSiguiiente.setEnabled(false);
        BtnUltimo.setEnabled(false);
        BtnEliminar.setEnabled(false);
        TxtCedula.setEnabled(true);
        TxtCedula.requestFocus();
        TxtCedula.setText("");
        BtnBuscar.setEnabled(false);

        habilitar();
        limpiar();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        datos.DeleteEmpleados(TxtCedula.getText());
        limpiar();
        inhabilitar();
        Fila = 1;
        ExtraerDatos(Fila);
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        BtnNuevo.setEnabled(true);
        BtnEditar.setEnabled(true);
        BtnModificar.setVisible(false);
        BtnGrabar.setVisible(true);
        BtnGrabar.setEnabled(false);
        inhabilitar();
        BtnPrimero.setEnabled(true);
        BtnAnterior.setEnabled(true);
        BtnSiguiiente.setEnabled(true);
        BtnUltimo.setEnabled(true);
        BtnEliminar.setEnabled(true);
        BtnBuscar.setEnabled(false);
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        int x=0;
        if(TxtUsuario.getText().length()!=0){
            x=1;
        }
        else
        {
            x=2;
        }

        if (x==1){

            limpiar();
            TxtCedula.setEnabled(true);
            TxtCedula.requestFocus();
            BtnPrimero.setEnabled(false);
            BtnAnterior.setEnabled(false);
            BtnSiguiiente.setEnabled(false);
            BtnUltimo.setEnabled(false);
            BtnNuevo.setEnabled(false);
            BtnEditar.setEnabled(false);
            BtnGrabar.setEnabled(false);
            BtnDeshacer.setEnabled(true);
            BtnEliminar.setEnabled(false);

            if (TxtCedula.getText().length() == 0){
                //JOptionPane.showMessageDialog(rootPane,"Debe digitar cedula");
                TxtCedula.requestFocus();

            }
        }
        if(x==2){

            Fila = 1;
            cargarDatos(TxtCedula.getText());
            BtnNuevo.setEnabled(true);
            BtnModificar.setEnabled(true);
            BtnEliminar.setEnabled(true);
            BtnPrimero.setEnabled(true);
            BtnAnterior.setEnabled(true);
            BtnSiguiiente.setEnabled(true);
            BtnUltimo.setEnabled(true);
            BtnEditar.setEnabled(true);

        }

    }//GEN-LAST:event_BtnBuscarActionPerformed

    
 private void ExtraerDatos(int Fila){      
        ClsUsuarios[] usuarios = new ClsUsuarios[1];
        try {            
           usuarios = ClsConUsuarios.SelectAll(Fila);
           NumberFormat Format = NumberFormat.getCurrencyInstance(Locale.getDefault());
            TxtCedula.setText(usuarios[0].getCedula());
            TxtUsuario.setText(usuarios[0].getNombre());
            TxtContraseña.setText(usuarios[0].getApellidos());
            TxtApellidos.setText(usuarios[0].getContraseña());
            CboTipoUsuario.setSelectedItem(usuarios[0].getTipoUsuario());
            
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }

     private void cargarDatos(String Cedula){      
        ClsUsuarios[] Usuarios = new ClsUsuarios[1];
        try {            
           Usuarios = ClsConUsuarios.buscar(Cedula);
            TxtCedula.setText(Usuarios[0].getCedula());
            TxtUsuario.setText(Usuarios[0].getNombre());
            TxtContraseña.setText(Usuarios[0].getApellidos());
            TxtApellidos.setText(Usuarios[0].getContraseña());
            CboTipoUsuario.setSelectedItem(Usuarios[0].getTipoUsuario());
            
        } catch (Exception ee) {
            System.out.println(ee.getStackTrace());
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmusuarios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnDeshacer;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnPrimero;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSiguiiente;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JComboBox CboTipoUsuario;
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JTextField TxtContraseña;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
